from sqlalchemy import Column, Integer, String
from database import Base

class UserProfile(Base):
    __tablename__ = "home_userprofile"  # Table name as generated by Django

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(255))
    email = Column(String(255), unique=True, index=True)
    password = Column(String(255))
    confirm_password = Column(String(255))
    mobile = Column(String(15))
    profile_photo = Column(String(255), nullable=True)
    status = Column(String(10), default='waiting')
